title: Michael Jonathan Panjaitan
logo: /assets/img/profile-picture.jpg
# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal # merlot, midnight, minimal, modernist, slate
